// pellicula.cpp — VCV Rack 2 module
// "Exploded" 8-voice drum sampler in the spirit of the Erica Synths Pico DRUM
// (original sample-player engine), rebuilt clean-room from the published manual.
//
//   - 8 independent one-shot sample-player voices
//   - each voice: sample-select, pitch, decay and level, with a knob + CV per
//     parameter and a manual + CV trigger
//   - poly normalling: every input row has a poly jack (channel N drives voice N)
//     plus 8 mono jacks; a mono jack overrides its voice's poly channel
//   - per-voice outs, a poly out (8 channels) and a summed mix out
//   - 12-bit playback grit (context menu toggle) and per-voice choke groups
//
// No samples are bundled. The user points the module at a global "kits folder"
// (saved plugin-wide); each immediate subfolder is a kit of up to 64 .wav files,
// ordered by filename. Kits load on a background thread and are swapped in
// glitch-free. Panel art is generated by tools/panels/gen_pellicula_panel.py.

#include "forsitan.hpp"
#include <osdialog.h>
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <cctype>
#include <cmath>
#include <algorithm>
#include <vector>
#include <memory>
#include <mutex>
#include <thread>
#include <atomic>

static const int kNumVoices  = 8;
static const int kNumSamples = 64;

// ── minimal WAV loader ────────────────────────────────────────────────────────
// Canonical RIFF/WAVE PCM. Handles 8/16/24/32-bit int and 32-bit float, mono or
// multi-channel (down-mixed to mono). Little-endian hosts only (all Rack targets).
struct Sample {
    std::vector<float> data;   // mono, normalised to [-1, 1]
    float sampleRate = 44100.f;
};

static uint32_t rd32(const uint8_t* p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static uint16_t rd16(const uint8_t* p) {
    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);
}

static bool loadWav(const std::string& path, Sample& out) {
    FILE* f = std::fopen(path.c_str(), "rb");
    if (!f)
        return false;
    std::fseek(f, 0, SEEK_END);
    long len = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    if (len < 44) { std::fclose(f); return false; }
    std::vector<uint8_t> buf(len);
    size_t got = std::fread(buf.data(), 1, len, f);
    std::fclose(f);
    if ((long)got != len)
        return false;

    if (std::memcmp(buf.data(), "RIFF", 4) != 0 || std::memcmp(buf.data() + 8, "WAVE", 4) != 0)
        return false;

    uint16_t fmt = 1, channels = 1, bits = 16;
    uint32_t rate = 44100;
    const uint8_t* pcm = nullptr;
    uint32_t pcmBytes = 0;

    size_t pos = 12;
    while (pos + 8 <= (size_t)len) {
        const uint8_t* ck = buf.data() + pos;
        uint32_t cksz = rd32(ck + 4);
        const uint8_t* body = ck + 8;
        if (std::memcmp(ck, "fmt ", 4) == 0 && cksz >= 16) {
            fmt      = rd16(body + 0);
            channels = rd16(body + 2);
            rate     = rd32(body + 4);
            bits     = rd16(body + 14);
        }
        else if (std::memcmp(ck, "data", 4) == 0) {
            pcm      = body;
            pcmBytes = cksz;
            if (pos + 8 + pcmBytes > (size_t)len)   // clamp to file
                pcmBytes = (uint32_t)((size_t)len - (pos + 8));
        }
        pos += 8 + cksz + (cksz & 1);   // chunks are word-aligned
    }
    if (!pcm || channels == 0)
        return false;

    const bool isFloat = (fmt == 3);
    const int  bytesPS = bits / 8;
    if (bytesPS == 0)
        return false;
    const uint32_t frames = pcmBytes / (bytesPS * channels);
    out.sampleRate = (float)rate;
    out.data.resize(frames);

    for (uint32_t i = 0; i < frames; ++i) {
        float acc = 0.f;
        for (int c = 0; c < channels; ++c) {
            const uint8_t* s = pcm + (size_t)(i * channels + c) * bytesPS;
            float v = 0.f;
            if (isFloat && bits == 32) {
                uint32_t u = rd32(s);
                float fv; std::memcpy(&fv, &u, 4);
                v = fv;
            }
            else if (bits == 16) {
                v = (int16_t)rd16(s) / 32768.f;
            }
            else if (bits == 24) {
                int32_t u = (s[0]) | (s[1] << 8) | (s[2] << 16);
                if (u & 0x800000) u |= ~0xFFFFFF;   // sign-extend
                v = u / 8388608.f;
            }
            else if (bits == 32) {
                v = (int32_t)rd32(s) / 2147483648.f;
            }
            else if (bits == 8) {
                v = ((int)s[0] - 128) / 128.f;   // 8-bit WAV is unsigned
            }
            acc += v;
        }
        out.data[i] = acc / channels;
    }
    return true;
}

// A loaded kit: up to 64 samples, ordered by filename.
struct Bank {
    std::string name;
    std::vector<Sample> samples;
};

// ── global "kits folder" setting (plugin-wide, shared by all instances) ───────
static std::mutex g_settingsMutex;
static std::string g_kitsFolder;
static bool g_settingsLoaded = false;

static std::string settingsPath() {
    return asset::user("pellicula/settings.json");
}
static void loadSettingsOnce() {
    std::lock_guard<std::mutex> lock(g_settingsMutex);
    if (g_settingsLoaded)
        return;
    g_settingsLoaded = true;
    FILE* f = std::fopen(settingsPath().c_str(), "r");
    if (!f)
        return;
    json_error_t err;
    json_t* root = json_loadf(f, 0, &err);
    std::fclose(f);
    if (!root)
        return;
    if (json_t* kf = json_object_get(root, "kitsFolder"))
        g_kitsFolder = json_string_value(kf);
    json_decref(root);
}
static std::string getKitsFolder() {
    std::lock_guard<std::mutex> lock(g_settingsMutex);
    return g_kitsFolder;
}
static void setKitsFolder(const std::string& path) {
    std::lock_guard<std::mutex> lock(g_settingsMutex);
    g_kitsFolder = path;
    system::createDirectories(system::getDirectory(settingsPath()));
    json_t* root = json_object();
    json_object_set_new(root, "kitsFolder", json_string(path.c_str()));
    if (FILE* f = std::fopen(settingsPath().c_str(), "w")) {
        json_dumpf(root, f, JSON_INDENT(2));
        std::fclose(f);
    }
    json_decref(root);
}

// natural (numeric-aware, case-insensitive) filename ordering: 1, 2, 10 not 1, 10, 2
static bool naturalLess(const std::string& A, const std::string& B) {
    std::string a = string::lowercase(A), b = string::lowercase(B);
    size_t i = 0, j = 0;
    while (i < a.size() && j < b.size()) {
        if (std::isdigit((unsigned char)a[i]) && std::isdigit((unsigned char)b[j])) {
            size_t i0 = i, j0 = j;
            while (i < a.size() && std::isdigit((unsigned char)a[i])) ++i;
            while (j < b.size() && std::isdigit((unsigned char)b[j])) ++j;
            std::string na = a.substr(i0, i - i0), nb = b.substr(j0, j - j0);
            size_t pa = na.find_first_not_of('0'), pb = nb.find_first_not_of('0');
            na = (pa == std::string::npos) ? "" : na.substr(pa);
            nb = (pb == std::string::npos) ? "" : nb.substr(pb);
            if (na.size() != nb.size()) return na.size() < nb.size();
            if (na != nb)               return na < nb;
        }
        else {
            if (a[i] != b[j]) return a[i] < b[j];
            ++i; ++j;
        }
    }
    return a.size() < b.size();
}

// list the immediate subfolders of the kits folder (each is a selectable kit)
static std::vector<std::string> listKits(const std::string& folder) {
    std::vector<std::string> kits;
    if (folder.empty() || !system::isDirectory(folder))
        return kits;
    for (const std::string& e : system::getEntries(folder))
        if (system::isDirectory(e))
            kits.push_back(system::getFilename(e));
    std::sort(kits.begin(), kits.end(), naturalLess);
    return kits;
}

// ── module ────────────────────────────────────────────────────────────────────
struct Pellicula : Module {
    enum ParamId {
        ENUMS(SAMPLE_PARAM, kNumVoices),
        ENUMS(PITCH_PARAM,  kNumVoices),
        ENUMS(DECAY_PARAM,  kNumVoices),
        ENUMS(LEVEL_PARAM,  kNumVoices),
        ENUMS(TRIG_PARAM,   kNumVoices),
        PARAMS_LEN
    };
    enum InputId {
        ENUMS(TRIG_INPUT,   kNumVoices),
        TRIG_POLY_INPUT,
        ENUMS(SAMPLE_INPUT, kNumVoices),
        SAMPLE_POLY_INPUT,
        ENUMS(PITCH_INPUT,  kNumVoices),
        PITCH_POLY_INPUT,
        ENUMS(DECAY_INPUT,  kNumVoices),
        DECAY_POLY_INPUT,
        ENUMS(LEVEL_INPUT,  kNumVoices),
        LEVEL_POLY_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        ENUMS(VOICE_OUTPUT, kNumVoices),
        POLY_OUTPUT,
        MIX_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        ENUMS(VOICE_LIGHT, kNumVoices),
        LIGHTS_LEN
    };

    struct Voice {
        bool   active   = false;
        double pos      = 0.0;   // playback position in source frames
        int    sample   = 0;     // latched sample index
        float  env      = 1.f;   // decay envelope
        float  envCoef  = 1.f;   // per-sample decay multiplier (1 = no decay)
        bool   noDecay  = true;  // full-sample playback (decay knob at max)
        std::shared_ptr<Bank> src;   // bank this voice is playing from (latched)
    };
    Voice voices[kNumVoices];
    dsp::SchmittTrigger trig[kNumVoices];
    int   chokeGroup[kNumVoices] = {0};   // 0 = none, 1..8 = group id
    bool  crush12 = true;                 // 12-bit playback grit
    float lightEnv[kNumVoices] = {0.f};

    // kit loading (background thread → glitch-free swap into `bank`)
    std::shared_ptr<Bank> bank;           // current kit (audio thread reads)
    std::string kitName;                  // selected kit subfolder name ("" = none)
    std::thread loader;
    std::mutex  handoffMutex;
    std::shared_ptr<Bank> incoming;       // staged by worker, consumed in process()
    std::atomic<bool> hasIncoming{false};
    std::atomic<bool> abortLoad{false};

    Pellicula() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);
        for (int v = 0; v < kNumVoices; ++v) {
            configParam(SAMPLE_PARAM + v, 1.f, (float)kNumSamples, (float)(v + 1), string::f("Voice %d sample", v + 1));
            getParamQuantity(SAMPLE_PARAM + v)->snapEnabled = true;
            configParam(PITCH_PARAM + v, -2.f, 2.f, 0.f, string::f("Voice %d pitch", v + 1), " oct");
            configParam(DECAY_PARAM + v,  0.f, 1.f, 1.f, string::f("Voice %d decay", v + 1));
            configParam(LEVEL_PARAM + v,  0.f, 1.f, 0.8f, string::f("Voice %d level", v + 1), "%", 0.f, 100.f);
            configButton(TRIG_PARAM + v, string::f("Voice %d trigger", v + 1));

            configInput(TRIG_INPUT + v,   string::f("Voice %d trigger", v + 1));
            configInput(SAMPLE_INPUT + v, string::f("Voice %d sample select (1V/oct, semitone)", v + 1));
            configInput(PITCH_INPUT + v,  string::f("Voice %d pitch (1V/oct)", v + 1));
            configInput(DECAY_INPUT + v,  string::f("Voice %d decay", v + 1));
            configInput(LEVEL_INPUT + v,  string::f("Voice %d level", v + 1));
            configOutput(VOICE_OUTPUT + v, string::f("Voice %d", v + 1));
            configLight(VOICE_LIGHT + v, string::f("Voice %d activity", v + 1));
        }
        configInput(TRIG_POLY_INPUT,   "Trigger (poly: channel N → voice N)");
        configInput(SAMPLE_POLY_INPUT, "Sample select (poly)");
        configInput(PITCH_POLY_INPUT,  "Pitch (poly)");
        configInput(DECAY_POLY_INPUT,  "Decay (poly)");
        configInput(LEVEL_POLY_INPUT,  "Level (poly)");
        configOutput(POLY_OUTPUT, "Polyphonic (8 voices)");
        configOutput(MIX_OUTPUT,  "Mix");

        loadSettingsOnce();
    }

    ~Pellicula() {
        abortLoad.store(true);
        if (loader.joinable())
            loader.join();
    }

    // Build a kit on a worker thread, then stage it for the audio thread.
    void loadKitWorker(std::string name) {
        auto b = std::make_shared<Bank>();
        b->name = name;
        std::string folder = getKitsFolder();
        std::string dir = folder + "/" + name;
        if (!name.empty() && !folder.empty() && system::isDirectory(dir)) {
            std::vector<std::string> files;
            for (const std::string& e : system::getEntries(dir)) {
                if (system::isFile(e) && string::lowercase(system::getExtension(e)) == ".wav")
                    files.push_back(e);
            }
            std::sort(files.begin(), files.end(), [](const std::string& x, const std::string& y) {
                return naturalLess(system::getFilename(x), system::getFilename(y));
            });
            if ((int)files.size() > kNumSamples)
                files.resize(kNumSamples);
            for (const std::string& fp : files) {
                if (abortLoad.load())
                    return;
                Sample s;
                if (!loadWav(fp, s))
                    s = Sample();          // keep index alignment with the file list
                b->samples.push_back(std::move(s));
            }
        }
        if (abortLoad.load())
            return;
        std::lock_guard<std::mutex> lock(handoffMutex);
        incoming = b;
        hasIncoming.store(true);
    }

    // (re)start a kit load. Runs on the UI/engine thread, never the audio thread.
    void loadKit(const std::string& name) {
        abortLoad.store(true);
        if (loader.joinable())
            loader.join();
        abortLoad.store(false);
        hasIncoming.store(false);
        kitName = name;
        loader = std::thread(&Pellicula::loadKitWorker, this, name);
    }

    bool readCV(int monoId, int polyId, int voice, float& outV) {
        if (inputs[monoId].isConnected()) {
            outV = inputs[monoId].getVoltage();
            return true;
        }
        if (inputs[polyId].isConnected() && voice < inputs[polyId].getChannels()) {
            outV = inputs[polyId].getVoltage(voice);
            return true;
        }
        return false;
    }

    void triggerVoice(int v) {
        // choke: silence other active voices sharing this voice's group
        if (chokeGroup[v] != 0) {
            for (int w = 0; w < kNumVoices; ++w)
                if (w != v && chokeGroup[w] == chokeGroup[v])
                    voices[w].active = false;
        }

        // latch sample index: knob (1..64) plus semitone-quantized CV, 0V = knob
        int idx = (int)std::round(params[SAMPLE_PARAM + v].getValue()) - 1;
        float cv;
        if (readCV(SAMPLE_INPUT + v, SAMPLE_POLY_INPUT, v, cv))
            idx += (int)std::round(cv * 12.f);
        if (idx < 0)
            idx = 0;

        Voice& vo = voices[v];
        // nothing to play if no kit, index past the kit, or empty slot
        if (!bank || idx >= (int)bank->samples.size() || bank->samples[idx].data.size() < 2) {
            vo.active = false;
            return;
        }
        vo.src    = bank;
        vo.sample = idx;

        // latch decay envelope from the current decay value
        float d = params[DECAY_PARAM + v].getValue();
        if (readCV(DECAY_INPUT + v, DECAY_POLY_INPUT, v, cv))
            d = clamp(d + cv * 0.1f, 0.f, 1.f);
        vo.noDecay = (d >= 0.995f);
        if (vo.noDecay) {
            vo.envCoef = 1.f;
        }
        else {
            float tau = 0.005f * std::pow(1000.f, d);   // 5 ms .. 5 s
            vo.envCoef = std::exp(-1.f / (tau * APP->engine->getSampleRate()));
        }
        vo.pos    = 0.0;
        vo.env    = 1.f;
        vo.active = true;
    }

    void process(const ProcessArgs& args) override {
        // consume a freshly-loaded kit (rare; only just after a load completes)
        if (hasIncoming.load(std::memory_order_acquire) && handoffMutex.try_lock()) {
            if (hasIncoming.load()) {
                bank = incoming;
                incoming.reset();
                hasIncoming.store(false);
            }
            handoffMutex.unlock();
        }

        float mix = 0.f;
        for (int v = 0; v < kNumVoices; ++v) {
            // ── trigger sources: mono jack / poly channel / manual button ──
            float trigV = 0.f;
            if (inputs[TRIG_INPUT + v].isConnected())
                trigV = inputs[TRIG_INPUT + v].getVoltage();
            else if (inputs[TRIG_POLY_INPUT].isConnected() && v < inputs[TRIG_POLY_INPUT].getChannels())
                trigV = inputs[TRIG_POLY_INPUT].getVoltage(v);
            if (params[TRIG_PARAM + v].getValue() > 0.5f)
                trigV = 10.f;
            if (trig[v].process(trigV, 0.1f, 1.f))
                triggerVoice(v);

            // ── render voice ──
            float out = 0.f;
            Voice& vo = voices[v];
            if (vo.active) {
                Sample& s = vo.src->samples[vo.sample];
                int i0 = (int)vo.pos;
                float fr = (float)(vo.pos - i0);
                float a = s.data[i0];
                float b = (i0 + 1 < (int)s.data.size()) ? s.data[i0 + 1] : 0.f;
                float smp = a + (b - a) * fr;

                if (crush12)
                    smp = std::round(smp * 2048.f) / 2048.f;   // 12-bit

                // level (knob + CV, live)
                float lvl = params[LEVEL_PARAM + v].getValue();
                float cv;
                if (readCV(LEVEL_INPUT + v, LEVEL_POLY_INPUT, v, cv))
                    lvl = clamp(lvl + cv * 0.1f, 0.f, 1.f);
                smp *= vo.env * lvl;
                out = smp * 5.f;

                // advance playback (resample for host SR and pitch)
                float pitch = params[PITCH_PARAM + v].getValue();
                if (readCV(PITCH_INPUT + v, PITCH_POLY_INPUT, v, cv))
                    pitch += cv;
                double rate = (double)(s.sampleRate / args.sampleRate) * std::pow(2.f, pitch);
                vo.pos += rate;
                if (!vo.noDecay)
                    vo.env *= vo.envCoef;

                if (vo.pos >= s.data.size() - 1 || vo.env < 1e-4f) {
                    vo.active = false;
                    vo.src.reset();
                }
            }

            outputs[VOICE_OUTPUT + v].setVoltage(out);
            outputs[POLY_OUTPUT].setVoltage(out, v);
            mix += out;

            // activity LED (fast attack, slow release)
            float a = std::fabs(out) * 0.2f;
            lightEnv[v] = std::max(a, lightEnv[v] - lightEnv[v] * 0.0005f);
            lights[VOICE_LIGHT + v].setBrightness(std::min(lightEnv[v], 1.f));
        }

        outputs[POLY_OUTPUT].setChannels(kNumVoices);
        outputs[MIX_OUTPUT].setVoltage(clamp(mix, -10.f, 10.f));
    }

    json_t* dataToJson() override {
        json_t* root = json_object();
        json_object_set_new(root, "crush12", json_boolean(crush12));
        json_object_set_new(root, "kit", json_string(kitName.c_str()));
        json_t* cg = json_array();
        for (int v = 0; v < kNumVoices; ++v)
            json_array_append_new(cg, json_integer(chokeGroup[v]));
        json_object_set_new(root, "chokeGroups", cg);
        return root;
    }

    void dataFromJson(json_t* root) override {
        if (json_t* c = json_object_get(root, "crush12"))
            crush12 = json_boolean_value(c);
        if (json_t* cg = json_object_get(root, "chokeGroups")) {
            for (int v = 0; v < kNumVoices && v < (int)json_array_size(cg); ++v)
                chokeGroup[v] = (int)json_integer_value(json_array_get(cg, v));
        }
        if (json_t* k = json_object_get(root, "kit")) {
            std::string name = json_string_value(k);
            if (!name.empty())
                loadKit(name);
        }
    }
};

// ── panel geometry (mm) — must match tools/panels/gen_pellicula_panel.py ─────────────
static const float PANEL_W = 111.76f;   // 22 HP
// column x: [0] = poly, [1..8] = voices
static const float COLX[kNumVoices + 1] =
    {18.f, 28.5f, 39.f, 49.5f, 60.f, 70.5f, 81.f, 91.5f, 102.f};
static const float MIX_X       = 7.f;
static const float TRIG_BTN_Y  = 16.0f;
static const float TRIG_JACK_Y = 26.0f;
static const float SAMP_KNOB_Y = 35.5f;
static const float SAMP_JACK_Y = 45.0f;
static const float PIT_KNOB_Y  = 54.5f;
static const float PIT_JACK_Y  = 64.0f;
static const float DEC_KNOB_Y  = 73.5f;
static const float DEC_JACK_Y  = 83.0f;
static const float LVL_KNOB_Y  = 92.5f;
static const float LVL_JACK_Y  = 102.0f;
static const float OUT_JACK_Y  = 112.0f;

struct PelliculaWidget : ModuleWidget {
    PelliculaWidget(Pellicula* module) {
        setModule(module);
        setPanel(createPanel(asset::plugin(pluginInstance, "res/pellicula.svg")));

        addChild(createWidget<ScrewSilver>(mm2px(Vec(5.08f, 0.f))));
        addChild(createWidget<ScrewSilver>(mm2px(Vec(PANEL_W - 10.16f, 0.f))));
        addChild(createWidget<ScrewSilver>(mm2px(Vec(5.08f, 123.42f))));
        addChild(createWidget<ScrewSilver>(mm2px(Vec(PANEL_W - 10.16f, 123.42f))));

        // per-voice columns
        for (int v = 0; v < kNumVoices; ++v) {
            float x = COLX[v + 1];
            addParam(createParamCentered<TL1105>(mm2px(Vec(x, TRIG_BTN_Y)), module, Pellicula::TRIG_PARAM + v));
            addChild(createLightCentered<SmallLight<GreenLight>>(mm2px(Vec(x + 3.2f, TRIG_BTN_Y + 3.5f)), module, Pellicula::VOICE_LIGHT + v));
            addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, TRIG_JACK_Y)), module, Pellicula::TRIG_INPUT + v));
            addParam(createParamCentered<Trimpot>(mm2px(Vec(x, SAMP_KNOB_Y)), module, Pellicula::SAMPLE_PARAM + v));
            addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, SAMP_JACK_Y)), module, Pellicula::SAMPLE_INPUT + v));
            addParam(createParamCentered<Trimpot>(mm2px(Vec(x, PIT_KNOB_Y)), module, Pellicula::PITCH_PARAM + v));
            addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, PIT_JACK_Y)), module, Pellicula::PITCH_INPUT + v));
            addParam(createParamCentered<Trimpot>(mm2px(Vec(x, DEC_KNOB_Y)), module, Pellicula::DECAY_PARAM + v));
            addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, DEC_JACK_Y)), module, Pellicula::DECAY_INPUT + v));
            addParam(createParamCentered<Trimpot>(mm2px(Vec(x, LVL_KNOB_Y)), module, Pellicula::LEVEL_PARAM + v));
            addInput(createInputCentered<PJ301MPort>(mm2px(Vec(x, LVL_JACK_Y)), module, Pellicula::LEVEL_INPUT + v));
            addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(x, OUT_JACK_Y)), module, Pellicula::VOICE_OUTPUT + v));
        }

        // poly column
        float px = COLX[0];
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(px, TRIG_JACK_Y)), module, Pellicula::TRIG_POLY_INPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(px, SAMP_JACK_Y)), module, Pellicula::SAMPLE_POLY_INPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(px, PIT_JACK_Y)), module, Pellicula::PITCH_POLY_INPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(px, DEC_JACK_Y)), module, Pellicula::DECAY_POLY_INPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(px, LVL_JACK_Y)), module, Pellicula::LEVEL_POLY_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(px, OUT_JACK_Y)), module, Pellicula::POLY_OUTPUT));

        // mix out (left gutter, output row)
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(MIX_X, OUT_JACK_Y)), module, Pellicula::MIX_OUTPUT));
    }

    void appendContextMenu(Menu* menu) override {
        Pellicula* m = dynamic_cast<Pellicula*>(module);
        std::string folder = getKitsFolder();

        menu->addChild(new MenuSeparator);
        menu->addChild(createMenuLabel(folder.empty() ? "Kits folder: (not set)"
                                                      : "Kits folder: " + folder));
        menu->addChild(createMenuItem("Set kits folder…", "", [=]() {
            char* p = osdialog_file(OSDIALOG_OPEN_DIR,
                                    folder.empty() ? NULL : folder.c_str(), NULL, NULL);
            if (p) {
                setKitsFolder(p);
                std::free(p);
            }
        }));
        if (!folder.empty())
            menu->addChild(createMenuItem("Clear kits folder", "", [=]() { setKitsFolder(""); }));

        menu->addChild(createSubmenuItem("Kit", m->kitName.empty() ? "none" : m->kitName, [=](Menu* sub) {
            std::string f = getKitsFolder();
            if (f.empty()) {
                sub->addChild(createMenuLabel("Set a kits folder first"));
                return;
            }
            std::vector<std::string> kits = listKits(f);
            if (kits.empty()) {
                sub->addChild(createMenuLabel("No kits (subfolders) found"));
                return;
            }
            sub->addChild(createCheckMenuItem("(none)", "",
                [=]() { return m->kitName.empty(); },
                [=]() { m->loadKit(""); }));
            for (const std::string& k : kits)
                sub->addChild(createCheckMenuItem(k, "",
                    [=]() { return m->kitName == k; },
                    [=]() { m->loadKit(k); }));
        }));

        // audition the kit in banks of 8: shift every slot's sample by ±8 (wrapping)
        auto shiftSamples = [=](int delta) {
            for (int v = 0; v < kNumVoices; ++v) {
                int cur = (int)std::round(m->params[Pellicula::SAMPLE_PARAM + v].getValue());
                int nxt = ((cur - 1 + delta) % kNumSamples + kNumSamples) % kNumSamples + 1;
                m->params[Pellicula::SAMPLE_PARAM + v].setValue((float)nxt);
            }
        };
        menu->addChild(createMenuItem("Shift all samples +8 (next bank)", "",
            [=]() { shiftSamples(+kNumVoices); }));
        menu->addChild(createMenuItem("Shift all samples -8 (previous bank)", "",
            [=]() { shiftSamples(-kNumVoices); }));

        menu->addChild(new MenuSeparator);
        menu->addChild(createBoolPtrMenuItem("12-bit playback grit", "", &m->crush12));
        menu->addChild(createSubmenuItem("Choke groups", "", [=](Menu* sub) {
            sub->addChild(createMenuLabel("Voices in the same group cut each other"));
            for (int v = 0; v < kNumVoices; ++v) {
                sub->addChild(createSubmenuItem(
                    string::f("Voice %d", v + 1),
                    m->chokeGroup[v] == 0 ? "none" : string::f("group %d", m->chokeGroup[v]),
                    [=](Menu* gsub) {
                        for (int g = 0; g <= kNumVoices; ++g) {
                            gsub->addChild(createCheckMenuItem(
                                g == 0 ? "none" : string::f("group %d", g), "",
                                [=]() { return m->chokeGroup[v] == g; },
                                [=]() { m->chokeGroup[v] = g; }));
                        }
                    }));
            }
        }));
    }
};

Model* modelPellicula = createModel<Pellicula, PelliculaWidget>("pellicula");
